### ISSUE TITLE
Verify Saturation of Wheel Launcher

### ISSUE THREAD

**Issue by dracco1993** [RAR1741/RA17_RobotCode#8]
We need to verify if speed control on the wheel launcher is saturating using the oscilloscope.

- [ ] Move the controller onto the table so we can have a better instrumentation setup.
- [ ] Make longer encoder extension cable

**Comment by snydecor000** [comment]
Mr. Meyer had me compare the CANTalon bus voltage to the output voltage and now we can calculate when the shooter saturates.

**Comment by dracco1993** [comment]
Awesome.  So this should be something we can do tonight, right?

**Comment by dracco1993** [comment]
This was done awhile ago.

We can reopen it if we need to do this again later on a real shooter.

**Comment by snydecor000** [comment]
This was done a long time ago... And moving the board onto the table isnt really needed anymore.
